# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0002_auto_20170905_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='tipo_acta',
            field=models.CharField(choices=[('Telegrama', 'Telegrama'), ('Certificado', 'Certificado'), ('Copia acta', 'Copia acta'), ('Mesa', 'Mesa')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
