# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import elecciones.models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0003_mesa_tipo_acta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesaDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acta', models.CharField(choices=[('Telegrama', 'Telegrama'), ('Certificado', 'Certificado'), ('Copia acta', 'Copia acta'), ('Mesa', 'Mesa')], max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=elecciones.models.path_foto_acta)),
            ],
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='tipo_acta',
        ),
        migrations.AddField(
            model_name='mesadocumento',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.Mesa'),
        ),
    ]
