# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import elecciones.models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0004_auto_20170920_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesadocumento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=elecciones.models.path_foto_documento),
        ),
    ]
